In this I am going to use the column transformer from scikit learn. For column wise normalization of the Iris dataset. 
What we want to do here:
--> Find mean of the column. 
--> Doing normalization and standardization on whole dataset at once. --> Using numpy or scikit learn. 
--> Find the similarity matrix (co-variance) --> Using numpy or scikit learn. 

In [32]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

In [18]:
iris: pd.DataFrame = pd.read_csv('../../Downloads/Data for ML/iris.csv')
print(iris.head(3))

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa


Not only mean, you can calculate anything here like variance, standard deviation, median, percentile, quantile etc.

In [27]:
pl: np.ndarray = iris.iloc[:, 2].values
print(f'Mean of Petal length = {pl.mean():.4f}')
sl: np.ndarray = iris.iloc[:, 0].values
print(f'Mean of Sepal length = {sl.mean():.4f}')

Mean of Petal length = 3.7580
Mean of Sepal length = 5.8433


In [98]:
X = iris.iloc[:, :-1].values
scaler = StandardScaler().fit(X)
print(f'Mean and Standard Deviation of iris data set = {scaler.mean_.round(4)} and {scaler.scale_.round(4)}')
scaler_transform = scaler.transform(X)

# If I want to fit some new data in the above transform.
data = [[1, 1, 1, 1]]                          # --> It will calculate the standard values of this data using mean and variance of above data. eg (1 - 1.1993)/0.7597 = -0.262386.
data_transformed = scaler.transform(data)
print(data_transformed)

Mean and Standard Deviation of iris data set = [5.8433 3.0573 3.758  1.1993] and [0.8253 0.4344 1.7594 0.7597]
[[-5.86856386 -4.7359148  -1.56757623 -0.26238682]]


Using fit_transform directly. 

In [99]:
X = iris.iloc[:, :-1].values
scaler = StandardScaler().fit_transform(X)
if scaler_transform.all() == scaler.all():
    print(f'Yes')
else: print('No')

Yes


Covariance: --> If the data is standardized then multiplication of the matrix and it's transpose will be the covariance or the similarity matrix. 

Covariance matrix can be biased and Unbiased estimator. Numpy by default uses unbiased estimator. 

In [105]:
X = iris.iloc[:, :-1].values
scaler = StandardScaler().fit_transform(X)

X_cov = np.matmul(scaler.T,scaler)/(scaler.shape[0] - 1) 
print(X_cov)
print(np.cov(scaler.T))                           

[[ 1.00671141 -0.11835884  0.87760447  0.82343066]
 [-0.11835884  1.00671141 -0.43131554 -0.36858315]
 [ 0.87760447 -0.43131554  1.00671141  0.96932762]
 [ 0.82343066 -0.36858315  0.96932762  1.00671141]]
[[ 1.00671141 -0.11835884  0.87760447  0.82343066]
 [-0.11835884  1.00671141 -0.43131554 -0.36858315]
 [ 0.87760447 -0.43131554  1.00671141  0.96932762]
 [ 0.82343066 -0.36858315  0.96932762  1.00671141]]
